FROM docker.io/library/ubuntu:26.04 AS base

RUN apt update \
 && apt full-upgrade -y \
 && apt install -y ca-certificates curl \
 && install -m 0755 -d /etc/apt/keyrings \
 && curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc \
 && chmod a+r /etc/apt/keyrings/docker.asc \
 && echo "deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu oracular stable" > /etc/apt/sources.list.d/docker.list \
 && apt update

RUN apt install -y \
    $(apt list 2>/dev/null | grep 'tesseract-ocr-' | cut -d'/' -f1) \
    tzdata \
    openjdk-21-jre \
    ghostscript \
    unpaper \
    weasyprint \
    python3 \
    python3-distutils-extra \
    fonts-droid-fallback \
    fonts-dejavu \
    fonts-freefont-ttf \
    fonts-noto \
    pngquant \
    ocrmypdf \
    qpdf \
    docker-ce-cli

COPY --from=ghcr.io/astral-sh/uv:python3.14-trixie-slim /usr/local/bin/uv /usr/local/bin/uvx /bin/

RUN uv pip install --system --break-system-packages --no-cache "unoserver==3.7"

FROM base AS download

RUN apt install -y \
    curl \
    unzip

WORKDIR /opt

ARG DOCSPELL_VERSION=0.43.0
RUN curl -sLfo joex.zip "https://github.com/eikek/docspell/releases/download/v${DOCSPELL_VERSION}/docspell-joex-${DOCSPELL_VERSION}.zip" && \
  unzip joex.zip && \
  rm joex.zip && \
  mv docspell-joex-* docspell-joex && \
  rm docspell-joex/conf/docspell-joex.conf && \
  echo "$DOCSPELL_VERSION" > docspell-joex/version

FROM base

COPY --from=download /opt/docspell-joex /opt/docspell-joex

COPY joex-entrypoint.sh /opt/joex-entrypoint.sh

ENTRYPOINT ["/opt/joex-entrypoint.sh"]
EXPOSE 7878

